### ISSUE TITLE
about this dockerfile

### ISSUE THREAD

**Issue by jinwuxia** [kieker-monitoring-docker/tomcat#1]
I am not sure whether I can raise problem  here. If it is not proper, please forgive me.
I try to use Tomcat/Dockerfile to build image. In this dockerfile, it says that:
`ENV KIEKER_AGENT_BASE_URL "https://search.maven.org/remotecontent?filepath=net/kieker-monitoring/kieker"
RUN \
  wget -q "${KIEKER_AGENT_BASE_URL}/${KIEKER_AGENT_JAR_SRC}" -O "${KIEKER_AGENT_FOLDER}/${KIEKER_AGENT_JAR}" && \`

But I found above URL maybe invalid, so I modify it to : `https://oss.sonatype.org/content/groups/staging/net/kieker-monitoring/kieker/1.11/`

after that, I build image using this dockfile again, it reports error:
`step24: ....................../usr/local/tomcat/bin/catalina.sh] returned a non-zero code: 8`

I do not know what causes the error. How can I do for going through this step.

**Comment by duelle** [comment]
Hello j123kaishichufa,
the URL stored in `KIEKER_AGENT_BASE_URL` is just the base of the URL we use in the `wget` command afterwards. The resulting URL for `wget` ist: https://search.maven.org/remotecontent?filepath=net/kieker-monitoring/kieker/1.11/kieker-1.11-aspectj.jar
From here it seems to be a valid and working URL.
I could not find any issues when trying to reproduce the issue you are having. Could you please elaborate what exactly does not work in the current configuration of the `Dockerfile` or resulting container?

If you want to just use the container, I would recommend using the prebuilt one in the Docker Hub. Using this approach you do not have to build the container yourself but just download it (e.g. `docker run -t -i -p 8080:8080 kieker/tomcat:1.11`).

**Comment by jinwuxia** [comment]
@duelle 
Thank you for your reply. It worked now.

Also, I have another questions for help about using kieker to monitoring rpc. Because my new question is  about rpc monitoring use kieker, instead of this dockerfile. It might be not proper to describe issue here. 

So, my email is  j123kaishichufa@gmail.com  .  Could I  ask for your email address.  If so, I will describe the exact problem and  send the detail issue to you. 
Thank you again.

**Comment by duelle** [comment]
If you have Kieker-specific questions I would recommend to pose them on the mailing lists which you can find here: http://kieker-monitoring.net/support/
